[package]
name = "nelson"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.6.1"
bat = "0.26.1"
dirs = "6.0.0"
reqwest = { version = "0.13.1", features = ["json", "blocking"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
toml = "0.9.11"
